---
title: "Atelier 01"
subtitle: "Variables, fonctions, objets et bibliothèques"
author: "Yann Audin"
format: 
  revealjs:
    transition: slide
    navigation-mode: vertical
    theme: default
    footer: "Atelier 01"
    scrollable: true
---

# Python

<!--
quarto install extension grantmcdermott/quarto-revealjs-clean
quarto render Atelier_01_pres.qmd
Themes:

    beige
    blood
    dark
    default
    league
    moon
    night
    serif
    simple
    sky
    solarized

-->

## Les principes de Python

```{python}

print("import this\n")

print("> Beautiful is better than ugly.")
print("> Explicit is better than implicit.")
print("> Simple is better than complex.")
print("> Complex is better than complicated.")
print("> Flat is better than nested.")
print("> Sparse is better than dense.")
print("> Readability counts.")
print("> Special cases aren't special enough to break the rules.")
print("> Although practicality beats purity.")
print("> Errors should never pass silently.")
print("> Unless explicitly silenced.")
print("> In the face of ambiguity, refuse the temptation to guess.")
print("> There should be one-- and preferably only one --obvious way to do it.")
print("> Although that way may not be obvious at first unless you're Dutch.")
print("> Now is better than never.")
print("> Although never is often better than *right* now.")
print("> If the implementation is hard to explain, it's a bad idea.")
print("> If the implementation is easy to explain, it may be a good idea.")
print("> Namespaces are one honking great idea -- let's do more of those!")

```

## Python

- Haut niveau
- Programmation impérative
- Orienté objet
- Gestion automatique de la mémoire
- Forte communauté 
- Nombreuses bibliothèques spécialisées

# Variables

## Types

- string
- int
- float
- bool
- ...

## Opérateurs (int et float)

- +, -, /, *
- //, %, **
- ()
- +=, -=

## Opérateurs de comparaison

- ==, !=
- \>, <, >=, <=
- and, or, not
- in

## Déclarer et imprimer

x = True
print(x)

```{python}
x = True
print(x)
```

La structure de "print" : print(*objects, sep=' ', end='\n')

Aussi: nom = input("Écrivez ici votre nom :")

# Listes et autres structures

## Listes

Liste d'éléments ordonnés.

liste = [1, 4.6, True, "Hello world!"]
print(liste)

```{python}

liste = [1, 4.6, True, "Hello world!"]
print(liste)

```

::: {.callout-note}
Notes :
- Un type string peut être considérée comme une liste!
- Grâce aux indentations, on peut écrire un objet sur plusieurs lignes.
:::

## Accéder aux éléments d'une liste

- [n], [-n]
- [n:m], [n:], [:n]
- [::n]
- [::-1]

## Fonctions

- append
- pop
- remove
- index
- extend

Autres opérations

- len
- del

## Tuples

(1, 5.0, True, "Hello World!")

Listes immutables créées par défauts par Python.

- Accepte la plupart des opérations des listes.

## Dictionnaires

Associent une clé à des valeurs ou objets.

- Créés en utilisant "dict" ou la structure {"clé_1": élément_1, "clé_2": élément_2}
- Modifiés en utilisant les clés entre crochets : dict["clé"]

Autres fonctions

- get
- pop
- del

## Autres types pertinents

range(start, stop, step)

x = range(0, 10, 2)

```{python}

x = range(0, 10, 2)
for i in x:
	print(i)

```

set



# Structures de contrôle

## Conditions

- Conditions :
	- if
	- elif
	- else
	- match

## Boucles

- for
	- Possible d'itérer sur des objets plus complexes comme un dictionnaire!
- while
- Termes supplémentaires : break, continue

for i in range(0, 10, 1):
	print(i)

```{python}
for i in range(0, 10, 1):
	print(i)
```

import random

done = False

while not done:
	done = random.choice([True, False])

## Essais et contextes 

Essayer et donner des alternatives en cas d'erreur :

- try
- except
- finally

